### ISSUE TITLE
1. Create HTML code for first visit page 

### ISSUE THREAD

**Issue by mycoolletter** [Sava4/step-project-oop.github.io#3]
Implement very simple UI for first visit page . 
Items that should be implemented :
1) Header with a logo and Create button
2) Almost blank section with a centralized text "No items have been added"
3)  Use kebab-case( lisp-case) for class creation

**Comment by Sava4** [comment]
Did No items have been added with `:empty` css selector.
In case nothing is present inside this element the selector works.
